
register:
    path:     /register
    defaults: { _controller: AppBundle:User:register }


login:
    path:     /login
    defaults: { _controller: AppBundle:User:login }

logout:
    path:     /logout
    defaults: { _controller: AppBundle:User:logout }


user_profile:
    path:     /user
    defaults: { _controller: AppBundle:User:profile }
