AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        password:
            type: string
            length: 255
        email:
            type: string
            length: 255
        first_name:
            type: string
            length: 255
            nullable: true
        last_name:
            type: string
            length: 255
            nullable: true
        birth_date:
            type: string
            length: 255
            nullable: true
        phone:
            type: string
            length: 255
            nullable: true
        education:
            type: string
            length: 255
            nullable: true
        address:
            type: string
            length: 255
            nullable: true
        about:
            type: text
            nullable: true
            
    lifecycleCallbacks: {  }
